name: vere
version: 0.1.0
license: AGPL-3.0-only

executables:
  test:
    main: Main.hs
    source-dirs: app/test
    dependencies: ["urbit"]
    ghc-options:
      - -threaded
      - -rtsopts
      - "-with-rtsopts=-H1024m"
      - -fwarn-incomplete-patterns
      - -O2

  uterm:
    main: Main.hs
    source-dirs: app/uterm
    dependencies: ["urbit"]
    ghc-options:
      - -threaded
      - -rtsopts
      - "-with-rtsopts=-H4096m"
      - -fwarn-incomplete-patterns
      - -O2

  vere:
    main: Main.hs
    source-dirs: app/vere
    dependencies: ["urbit"]
    ghc-options:
      - -threaded
      - -rtsopts
      - "-with-rtsopts=-H128m"
      - -fwarn-incomplete-patterns
      - -O2

dependencies:
  - async
  - base
  - bytestring
  - case-insensitive
  - classy-prelude
  - conduit
  - containers
  - data-fix
  - directory
  - extra
  - flat
  - ghc-prim
  - hashtables
  - http-client
  - http-types
  - integer-gmp
  - largeword
  - lens
  - lmdb
  - megaparsec
  - mtl
  - multimap
  - para
  - pretty-show
  - primitive
  - process
  - QuickCheck
  - resourcet
  - sdl2
  - sdl2-image
  - semigroups
  - smallcheck
  - stm
  - stm-chans
  - tasty
  - tasty-quickcheck
  - tasty-th
  - text
  - these
  - time
  - transformers
  - unordered-containers
  - urbit
  - vector
  - wai
  - warp
  - warp-tls

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
