language: node_js # ish, mainly used as an entry point
before_install:
  - cd .travis # keep main directory clear
  
  - >
      wget $(cat ./pin-urbit-release.url)/urbit -O ./urbit &&
      chmod +x ./urbit;
      echo "FIXME downloaded raw urbit binary releaseinstead of .deb";
      echo "FIXME read full pinned url instead of tag name"
      
before_script: bash make-pill.sh
      
