language: node_js
node_js:
- 4

script:
  - meson . ./build --buildtype=debugoptimized -Dgc=true -Dprof=true
  - cd ./build
  - ninja
  - sudo ninja install
  - cd ../.travis
  - ulimit -c unlimited -S
  - npm install
  # || true so we continue
  - npm run -s test || RESULT=$?
  - if [[ ${RESULT} -eq 0 ]]; then exit 0; else for i in $(find ./ -maxdepth 1 -name 'core*' -print); do gdb urbit core* -ex "thread apply all bt" -ex "set pagination 0" -batch; done; fi;
  - echo "build failed with status code $RESULT"
  - exit $RESULT

# Uncomment me if this gets annoying
#
# notifications:
#   email: false

before_install:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - unzip ninja-linux.zip
  - sudo mv ninja /usr/bin/

install:
  # pwd: ~/urbit
  - pip3 install --user -I meson==0.46.1
  - git clone https://github.com/urbit/arvo
  - cd ./arvo
  - git checkout $(cat ../.travis/pin-arvo-commit.txt)
  - cd ..

addons:
  apt:
    packages:
    - python3
    - python3-pip
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libssl-dev
    - libncurses5-dev
    - automake
    - autoconf
    - make
    - libtool
    - g++
    - re2c
    - libcurl4-gnutls-dev
    - unzip
    - gdb
# before_deploy: "make deb" # TODO
deploy:
  skip_cleanup: true
  provider: releases
  prerelease: true # turn this off for official releases
  api_key:
    secure: V4E7784ECSS3MO6ZIRtang9XwibDyvDYGb0MoSaP2CTlmzIAhdokr4KJFM0qM4KRaaajCdQuqi0lojgOjwdxs7e0GkAwScb33LFxQ7Chj/QkFOY7V1AnSRLR5OsXnazB0nur5aSwvcvnggQ2XW3OeF7zIvGfs9aR97SEz/xCrVE=
  file: ./build/urbit # TODO upload package from before_deploy
  on:
    repo: urbit/urbit
    tags: true
