language: c
before_script:
  - curl -L https://github.com/libuv/libuv/archive/v1.x.tar.gz | tar xzf -
  - (cd libuv-1.x && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install)
script: make && make test # no ./configure

# Uncomment me if this gets annoying
#
# notifications: 
#   email: false 

addons:
  apt:
    packages:
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libssl-dev
    - libncurses5-dev
    - make
    - exuberant-ctags
    - automake
    - autoconf
    - libtool
    - g++
    - ragel
    - cmake
    - re2c
    - libcurl4-gnutls-dev
    - python

