resolver: lts-14.4

packages:
  - pkg/proto

extra-deps:
  - para-1.1@sha256:a90eebb063ad70271e6e2a7f00a93e8e8f8b77273f100f39852fbf8301926f81


nix:
  packages:
    - pkgconfig
    - SDL2
    - SDL2_image
    - zlib
