name: urbit
version: 0.1.0
license: AGPL-3.0-only

library:
  source-dirs: lib
  ghc-options:
    - -fwarn-incomplete-patterns
    - -fwarn-unused-binds
    - -fwarn-unused-imports
    - -Werror
    - -O2

tests:
  urbit-tests:
    source-dirs: test
    main: Main.hs
    dependencies: urbit
    ghc-options:
      - -threaded

dependencies:
  - async
  - base
  - bytestring
  - case-insensitive
  - classy-prelude
  - conduit
  - containers
  - data-fix
  - directory
  - entropy
  - extra
  - fixed-vector
  - flat
  - ghc-prim
  - hashable
  - hashtables
  - http-client
  - http-types
  - integer-gmp
  - iproute
  - largeword
  - lens
  - lmdb
  - megaparsec
  - mtl
  - multimap
  - network
  - para
  - pretty-show
  - primitive
  - process
  - QuickCheck
  - resourcet
  - rio
  - sdl2
  - sdl2-image
  - semigroups
  - smallcheck
  - stm
  - stm-chans
  - tasty
  - tasty-quickcheck
  - tasty-th
  - template-haskell
  - text
  - these
  - time
  - transformers
  - unordered-containers
  - vector
  - wai
  - warp
  - warp-tls

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
