name: build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - '.github/workflows/vere.yml'
      - 'bazel/**'
      - 'pkg/**'
  # pull_request:
  #   paths:
  #     - '.github/workflows/build.yml'
  #     - '.github/workflows/vere.yml'
  #     - 'bazel/**'
  #     - 'pkg/**'

jobs:
  call-vere:
    uses: ./.github/workflows/vere.yml
    with:
      pace: 'edge' # XX s/b once?
      upload: >-
        ${{
        (github.ref_name == 'next/vere' && github.ref_type == 'branch')
        }}
    secrets: inherit
