name: Push to develop

on:
  release: null
  push:
    branches:
      - develop

jobs:
  urbit:
    uses: ./.github/workflows/shared.yml
    with:
      pace: 'edge'
      upload: true
    secrets: inherit
