name: feature

on:
  push:
    paths:
      - '.bazelrc'
      - '.github/workflows/*.yml'
      - 'BUILD.bazel'
      - 'WORKSPACE.bazel'
      - 'bazel/**'
      - 'pkg/**'
    branches-ignore:
      - 'next/vere'
      - 'master'
  pull_request:
    paths:
      - '.bazelrc'
      - '.github/workflows/*.yml'
      - 'BUILD.bazel'
      - 'WORKSPACE.bazel'
      - 'bazel/**'
      - 'pkg/**'

jobs:
  call-vere:
    uses: ./.github/workflows/vere.yml
    with:
      upload: true