name: Push to master

on:
  release: null
  push:
    branches:
      - master

jobs:
  urbit:
    uses: ./.github/workflows/shared.yml
    with:
      docker: true
      pace: 'live'
      upload: true
    secrets: inherit
