name: vere

on:
  workflow_call:
    inputs:
      upload:
        description: 'upload binaries to gcp'
        type: boolean
        default: false
        required: false
      pace:
        description: 'release pace'
        type: string
        default: 'edge'
        required: false
    secrets:
      GCP_CREDENTIALS:
        required: false
      GCS_SERVICE_ACCOUNT_KEY:
        required: false
      GCS_PROJECT:
        required: false

  workflow_dispatch:
    inputs:
      upload:
        description: 'upload binaries to gcp'
        type: boolean
        default: false
        required: false
      pace:
        description: 'release pace'
        type: choice
        options:
        - edge
        - soon
        - live

env:
  UPLOAD_BASE: bootstrap.urbit.org/vere
  VERE_PACE: ${{ inputs.pace }}
  VERSION_TYPE: ${{ (inputs.pace == 'soon' || inputs.pace == 'live') && 'real' || 'hash' }}

jobs:
  urbit:
    strategy:
      fail-fast: false
      matrix:
        include:
          # - { host: linux-x86_64, target: linux-x86_64, toolchain: gcc, toolchain_version: 11, runner: ubuntu-22.04 }
          - { host: macos-x86_64, target: macos-x86_64, toolchain: clang, toolchain_version: 14.0.0, runner: macos-12 }

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: build static binary
        # TODO: configure vere pace
        run: |
          params=(
            --host_platform=//:${{ matrix.toolchain }}-${{ matrix.host }}
            --platforms=//:${{ matrix.target }}
            --${{ matrix.toolchain }}_version=${{ matrix.toolchain_version }}
          )
          if [[ "${{ matrix.host }}" == "macos"* ]]; then
            sudo xcode-select --switch /Library/Developer/CommandLineTools
            brew install automake
            XCODE_VERSION=14.0.1
            XCODE_INSTALL_PATH=/Applications/Xcode_${XCODE_VERSION}.app
            params+=(--sandbox_block_path=$XCODE_INSTALL_PATH)
          fi
          bazel build ... "${params[@]}"
          echo "$GITHUB_WORKSPACE/bazel-bin/pkg/vere/urbit"
          echo "urbit_static=$GITHUB_WORKSPACE/bazel-bin/pkg/vere/urbit" >> $GITHUB_ENV

      - name: run tests
        run: |
          params=(
            --host_platform=//:${{ matrix.toolchain }}-${{ matrix.host }},
            --platforms=//:${{ matrix.target }},
            --${{ matrix.toolchain }}_version=${{ matrix.toolchain_version }}
          )
          if [[ "${{ matrix.host }}" == "macos"* ]]; then
            brew install automake
            XCODE_VERSION=14.0.1
            XCODE_INSTALL_PATH=/Applications/Xcode_${XCODE_VERSION}.app
            params+=(--sandbox_block_path=$XCODE_INSTALL_PATH)
          fi
          bazel test ... "${params[@]}"