name: vere

on:
  workflow_call:
    inputs:
      upload:
        description: 'upload binaries to gcp'
        type: boolean
        default: false
        required: false
      pace:
        description: 'release pace'
        type: string
        default: 'edge'
        required: false
    secrets:
      GCP_CREDENTIALS:
        required: false
      GCS_SERVICE_ACCOUNT_KEY:
        required: false
      GCS_PROJECT:
        required: false

  workflow_dispatch:
    inputs:
      upload:
        description: 'upload binaries to gcp'
        type: boolean
        default: false
        required: false
      pace:
        description: 'release pace'
        type: choice
        options:
        - edge
        - soon
        - live

env:
  UPLOAD_BASE: bootstrap.urbit.org/vere
  VERE_PACE: ${{ inputs.pace }}
  VERSION_TYPE: ${{ (inputs.pace == 'soon' || inputs.pace == 'live') && 'real' || 'hash' }}

jobs:
  urbit:
    strategy:
      fail-fast: false
      matrix:
        include:
          # TODO: re-enable these after development
          - { host: linux-x86_64, target: linux-x86_64, toolchain: gcc, toolchain_version: 11, runner: ubuntu-22.04 }
          - { host: linux-x86_64, target: linux-arm64, toolchain: aarch64_linux_gnu_gcc, toolchain_version: 11, runner: ubuntu-22.04 }
          - { host: macos-x86_64, target: macos-x86_64, toolchain: clang, toolchain_version: 14.0.0, runner: macos-12 }

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: build static binary
        # NOTE: On GitHub's macOS hosted runners, Bazel fails to find our GMP
        # header file because it tries to find a system-installed GMP at
        # `/usr/local/include/gmp.h` instead of our project-local copy specified
        # in `bazel/third_party/gmp/gmp.BUILD`. To ameliorate this, we enable
        # sandboxing and block access to `/usr/local/include` in the sandbox.
        # The downside of this solution is that it "effectively disables any
        # cache the tool may have." When/if we want to use caching in our
        # automated macOS build, we must find a better solution.
        # See: https://bazel.build/docs/sandboxing
        run: |
          echo "${{ inputs.pace }}" > ./pkg/vere/PACE
          params=(
            --host_platform=//:${{ matrix.toolchain }}-${{ matrix.host }}
            --platforms=//:${{ matrix.target }}
            --${{ matrix.toolchain }}_version=${{ matrix.toolchain_version }}
          )
          if [[ "${{ matrix.host }}" == "macos"* ]]; then
            sudo xcode-select --switch /Library/Developer/CommandLineTools
            brew install automake libtool
            params+=(
              --sandbox_block_path=/usr/local/include
              --spawn_strategy=sandboxed
            )
          fi
          if [[ "${{ matrix.target }}" == "linux-arm64" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi
          bazel build :urbit "${params[@]}"
          echo "$GITHUB_WORKSPACE/bazel-bin/pkg/vere/urbit"
          echo "urbit_static=$GITHUB_WORKSPACE/bazel-bin/pkg/vere/urbit" >> $GITHUB_ENV

      - name: run tests
        # TODO: Remove this condition once https://github.com/urbit/vere/issues/15 is resolved.
        if: matrix.target != 'linux-arm64'
        run: |
          params=(
            --host_platform=//:${{ matrix.toolchain }}-${{ matrix.host }}
            --platforms=//:${{ matrix.target }}
            --${{ matrix.toolchain }}_version=${{ matrix.toolchain_version }}
          )
          if [[ "${{ matrix.host }}" == "macos"* ]]; then
            sudo xcode-select --switch /Library/Developer/CommandLineTools
            brew install automake libtool
            params+=(
              --sandbox_block_path=/usr/local/include
              --spawn_strategy=sandboxed
            )
          fi
          if [[ "${{ matrix.target }}" == "linux-arm64" ]]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi
          bazel test ... "${params[@]}"

      - name: upload binary to bootstrap.urbit.org
        if: inputs.upload
        run: |
          version="$(cat ./pkg/vere/VERSION)"
          os=$(echo "${{ matrix.target }}" | cut -d'-' -f1)
          arch=$(echo "${{ matrix.target }}" | cut -d'-' -f2)
          system=${arch}-${os}
          target="gs://${UPLOAD_BASE}/${VERE_PACE}/${version}/vere-v${version}-${system}"

          gsutil cp -n "${{ env.urbit_static }}/bin/urbit" "$target"
          exitcode=$?

          test $exitcode -eq 0 &&
            echo "upload to $target complete." ||
            echo "upload to $target failed.";
          exit $exitcode